package com.company;

import java.util.Random;
import java.util.Scanner;

//guess the number
class Game{
    int number;
    int inputNumber;
    int noOfGuesses=0;

    public int getNoOfGuesses() {
        return noOfGuesses;
    }

    public void setNoOfGuesses(int noOfGuesses) {
        this.noOfGuesses = noOfGuesses;
    }

    Game(){
        Random rand= new Random();
          number=rand.nextInt(100);
    }

    public void takeUserInput(){
        System.out.println("Guess the number");
        Scanner sc=new Scanner(System.in);
         inputNumber = sc.nextInt();
    }

    public boolean isCorrectNumber() {
        noOfGuesses++;
        if (inputNumber == number) {
            System.out.format("Yes you guessed it right! It was %d \n you guessed it in %d attempts", number,noOfGuesses);
            System.out.println();
            return true;
        }
        else if (inputNumber < number) {
            System.out.println("Too less..");
        }
        else if(inputNumber > number){
            System.out.println("Too much...");
        }
        return false;
    }
}
public class First_26_Guess_the_number {
    public static void main(String[] args) {
        Game g= new Game();
        boolean b=false;
        //Using while to continue and guess the number until it matches with the number generated by computer

        while(!b) {
            g.takeUserInput();
           b= g.isCorrectNumber();
            System.out.println(b);
        }
    }
}
